### ISSUE TITLE
Difficult to use without documentation

### ISSUE THREAD

**Issue by riban-bw** [ycollet/oscmidi#2]
The code compiled easily and runs well with sufficient --help to inform user how to run with appropriate parameters but I couldn't find documentation describing how to use it. I had to look at the source code to find out the OSC paths supported and parameter quantity and types. If this is described elsewhere, please provide a link. The README could include a short user guide and examples.

**Comment by ycollet** [comment]
OK, I will add some examples of use in the README ASAP.

**Comment by ycollet** [comment]
I added some informations related to OSC messages send wrt MIDI messages.
I also added start / continue / stop messages.

**Comment by riban-bw** [comment]
Thanks, that is great. What has been catching me out for days now is knowing the quantity of parameters, their types and their purpose for each message. Your updates to the README has shown the paths and quantity of parameters but does not state that they are all INT32 or what each parameter is, e.g. MIDI Channel, Controller Number, Value, etc. Providing this would further enhance the usefulness of the information. (Incidentally, I am yet to find an Android App that sends INT32 values for controllers - they all seem to send FLOAT32.)

**Comment by ycollet** [comment]
All parameters are int32 (the "iii" part in the lo_send function).

I will and some comments in the README.
